// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb3zfeEUbmY43GO3y3nTlZZ1lXobQwyzQ',
    appId: '1:733428326901:web:5f2148441d0769b22dc0bc',
    messagingSenderId: '733428326901',
    projectId: 'healtify-f504d',
    authDomain: 'healtify-f504d.firebaseapp.com',
    storageBucket: 'healtify-f504d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeiGrrJRsg2_JheULja7CFnFhLqpSXMMQ',
    appId: '1:733428326901:android:3ec914ee5af6fb3f2dc0bc',
    messagingSenderId: '733428326901',
    projectId: 'healtify-f504d',
    storageBucket: 'healtify-f504d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtA0i0jFWDQhLi1CVs1hcN2rqSo6p4p2I',
    appId: '1:733428326901:ios:448e423a3cb729c02dc0bc',
    messagingSenderId: '733428326901',
    projectId: 'healtify-f504d',
    storageBucket: 'healtify-f504d.appspot.com',
    iosClientId: '733428326901-upcg6rcp2t6cs5g9n2u4j5tbv2hjjnoo.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthApp',
  );
}
